2024-12-05 15:57:53,434-DCInside.log-INFO-__init__.py:485-[10352] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:30:09,089-DCInside.log-INFO-__init__.py:485-[10308] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:32:07,048-DCInside.log-ERROR-__init__.py:475-[5384] open Error: list index out of range

2024-12-05 16:32:07,048-DCInside.log-ERROR-__init__.py:476-[5384] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:32:17,303-DCInside.log-INFO-__init__.py:485-[13996] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:33:36,069-DCInside.log-INFO-__init__.py:499-[13996] closed
2024-12-05 16:33:46,631-DCInside.log-INFO-__init__.py:485-[1152] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:35:30,155-DCInside.log-INFO-__init__.py:485-[6532] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:35:57,738-DCInside.log-INFO-__init__.py:499-[6532] closed
2024-12-05 16:37:15,724-DCInside.log-INFO-__init__.py:485-[10320] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:37:27,316-DCInside.log-INFO-__init__.py:499-[10320] closed
2024-12-05 16:43:04,729-DCInside.log-INFO-__init__.py:485-[11312] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:43:15,831-DCInside.log-INFO-__init__.py:499-[11312] closed
2024-12-05 16:45:48,622-DCInside.log-INFO-__init__.py:485-[5676] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:45:55,023-DCInside.log-INFO-__init__.py:499-[5676] closed
2024-12-05 16:46:49,364-DCInside.log-ERROR-__init__.py:475-[7104] open Error: list index out of range

2024-12-05 16:46:49,365-DCInside.log-ERROR-__init__.py:476-[7104] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:46:55,292-DCInside.log-INFO-__init__.py:485-[8820] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:46:58,813-DCInside.log-INFO-__init__.py:499-[8820] closed
2024-12-05 16:48:27,274-DCInside.log-INFO-__init__.py:485-[16848] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:48:33,234-DCInside.log-INFO-__init__.py:499-[16848] closed
2024-12-05 16:48:51,110-DCInside.log-INFO-__init__.py:485-[3868] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:49:15,467-DCInside.log-INFO-__init__.py:485-[14104] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:49:58,680-DCInside.log-INFO-__init__.py:499-[14104] closed
2024-12-05 16:50:08,494-DCInside.log-ERROR-__init__.py:475-[13108] open Error: list index out of range

2024-12-05 16:50:08,494-DCInside.log-ERROR-__init__.py:476-[13108] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:50:15,524-DCInside.log-INFO-__init__.py:485-[10152] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:51:58,237-DCInside.log-ERROR-__init__.py:475-[6380] open Error: list index out of range

2024-12-05 16:51:58,237-DCInside.log-ERROR-__init__.py:476-[6380] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:52:03,845-DCInside.log-INFO-__init__.py:485-[15640] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:52:09,882-DCInside.log-INFO-__init__.py:499-[15640] closed
2024-12-05 16:52:20,971-DCInside.log-INFO-__init__.py:485-[5668] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:52:59,982-DCInside.log-INFO-__init__.py:485-[16464] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:54:44,668-DCInside.log-INFO-__init__.py:485-[12680] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:55:05,360-DCInside.log-INFO-__init__.py:485-[17208] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:55:40,272-DCInside.log-ERROR-__init__.py:475-[4348] open Error: list index out of range

2024-12-05 16:55:40,272-DCInside.log-ERROR-__init__.py:476-[4348] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:55:45,711-DCInside.log-INFO-__init__.py:485-[16164] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:56:10,088-DCInside.log-ERROR-__init__.py:475-[13504] open Error: list index out of range

2024-12-05 16:56:10,088-DCInside.log-ERROR-__init__.py:476-[13504] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:56:14,113-DCInside.log-ERROR-__init__.py:475-[1832] open Error: list index out of range

2024-12-05 16:56:14,113-DCInside.log-ERROR-__init__.py:476-[1832] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:56:19,043-DCInside.log-INFO-__init__.py:485-[7904] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:56:41,152-DCInside.log-INFO-__init__.py:485-[9884] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:57:09,474-DCInside.log-INFO-__init__.py:485-[15560] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:57:44,600-DCInside.log-ERROR-__init__.py:475-[2684] open Error: list index out of range

2024-12-05 16:57:44,600-DCInside.log-ERROR-__init__.py:476-[2684] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 16:57:52,619-DCInside.log-INFO-__init__.py:485-[8996] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 16:59:49,503-DCInside.log-INFO-__init__.py:485-[2884] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:00:17,336-DCInside.log-INFO-__init__.py:485-[12708] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:03:52,459-DCInside.log-INFO-__init__.py:485-[10476] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:04:43,175-DCInside.log-INFO-__init__.py:485-[16548] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:06:53,199-DCInside.log-INFO-__init__.py:485-[11496] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:07:37,008-DCInside.log-INFO-__init__.py:485-[6024] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:09:06,984-DCInside.log-INFO-__init__.py:485-[13024] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:09:30,577-DCInside.log-INFO-__init__.py:485-[12780] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:10:33,533-DCInside.log-INFO-__init__.py:485-[9684] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:15:09,985-DCInside.log-INFO-__init__.py:485-[13364] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:15:31,511-DCInside.log-INFO-__init__.py:499-[13364] closed
2024-12-05 17:16:07,921-DCInside.log-ERROR-__init__.py:475-[14100] open Error: list index out of range

2024-12-05 17:16:07,922-DCInside.log-ERROR-__init__.py:476-[14100] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-05 17:16:15,014-DCInside.log-INFO-__init__.py:485-[12800] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:17:03,571-DCInside.log-INFO-__init__.py:485-[3404] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:18:05,884-DCInside.log-INFO-__init__.py:485-[15504] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:18:24,928-DCInside.log-INFO-__init__.py:499-[15504] closed
2024-12-05 17:20:32,927-DCInside.log-INFO-__init__.py:485-[15372] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:20:46,856-DCInside.log-INFO-__init__.py:499-[15372] closed
2024-12-05 17:20:58,480-DCInside.log-INFO-__init__.py:485-[16236] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:28:34,114-DCInside.log-INFO-__init__.py:485-[13348] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:28:53,219-DCInside.log-INFO-__init__.py:499-[13348] closed
2024-12-05 17:34:14,921-DCInside.log-INFO-__init__.py:485-[7480] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:35:35,275-DCInside.log-INFO-__init__.py:485-[6580] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:36:06,228-DCInside.log-INFO-__init__.py:499-[6580] closed
2024-12-05 17:53:55,433-DCInside.log-INFO-__init__.py:485-[4472] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:54:30,272-DCInside.log-INFO-__init__.py:499-[4472] closed
2024-12-05 17:54:40,007-DCInside.log-INFO-__init__.py:485-[6952] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:56:11,319-DCInside.log-INFO-__init__.py:485-[10936] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-05 17:56:43,851-DCInside.log-INFO-__init__.py:499-[10936] closed
2024-12-05 17:57:08,546-DCInside.log-INFO-__init__.py:485-[2840] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 13:05:01,666-DCInside.log-INFO-__init__.py:485-[2644] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 13:15:18,472-DCInside.log-INFO-__init__.py:485-[1240] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:06:55,140-DCInside.log-INFO-__init__.py:485-[16376] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:07:25,611-DCInside.log-INFO-__init__.py:485-[8832] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:08:04,028-DCInside.log-INFO-__init__.py:485-[15620] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:09:00,704-DCInside.log-INFO-__init__.py:485-[13272] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:09:54,734-DCInside.log-INFO-__init__.py:485-[7272] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:10:16,306-DCInside.log-INFO-__init__.py:485-[1792] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:11:22,978-DCInside.log-INFO-__init__.py:485-[10324] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:12:07,836-DCInside.log-INFO-__init__.py:485-[10216] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:12:46,638-DCInside.log-INFO-__init__.py:485-[13044] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:13:28,787-DCInside.log-INFO-__init__.py:485-[2488] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:14:55,636-DCInside.log-INFO-__init__.py:485-[13264] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:15:31,497-DCInside.log-INFO-__init__.py:485-[14516] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:17:41,767-DCInside.log-INFO-__init__.py:485-[9044] open: get <https://www.dcinside.com/> with <1200,800>
2024-12-06 16:21:34,491-DCInside.log-ERROR-__init__.py:475-[292] open Error: list index out of range

2024-12-06 16:21:34,491-DCInside.log-ERROR-__init__.py:476-[292] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


2024-12-06 16:21:39,243-DCInside.log-ERROR-__init__.py:475-[3216] open Error: list index out of range

2024-12-06 16:21:39,243-DCInside.log-ERROR-__init__.py:476-[3216] Traceback (most recent call last):
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 468, in __init__
    self.browser_version = self._get_browser_version()
  File "C:\Users\argos\Desktop\data_extract\modules\dcinside\venv\lib\site-packages\alabslib\selenium\__init__.py", line 142, in _get_browser_version
    bv = lines[-1].split()[0]
IndexError: list index out of range


